### ISSUE TITLE
Template_Extraction_and_Validation is very slow

### ISSUE THREAD

**Issue by Alwin-Bucher** [reymond-group/CASP-and-dataset-performance#2]
Hi,

I just wanted to say that the `process_reaction_data` function in `Template_Extraction_and_Validation.py` is much slower than it needs to be (i.e. taking multiple days to run on the whole USPTO dataset on my machine). I realise this is not something that needs to be run too many times, but even in my case it was faster to rewrite it/the `import_USPTO` method using pandas' `apply`. I'd be happy to submit a pull request for the changes.

**Comment by SGenheden** [comment]
Hello
Glad you are using the code. Please go ahead and submit a pull request.
I am in charge of re-factoring parts of this codebase, so speaking only from perspective - I would greatly appreciate your suggestions.

**Comment by A-Thakkar** [comment]
Sure go ahead, that would be much appreciated
